security:
  enable_authenticator_manager: true

  encoders:
    App\Entity\User:
      algorithm: auto

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    user:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    api:
      pattern: ^/api/
      custom_authenticators:
        - App\Security\ApiTokenAuthenticator
