version: '3.7'

services:
  postgres:
    env_file:
      - .env
    hostname: db
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - PostgresData:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/var/www

  caddy:
    env_file:
      - .env
    image: caddy:2.3.0-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - .:/var/www
      - .docker/caddy/:/etc/caddy/
      - CaddyConfig:/config
      - CaddyData:/data

volumes:
  PostgresData:
  CaddyConfig:
  CaddyData:
